
apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-reset-password
spec:
  template:
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "yourpassword"  # The current root password (if any)
        command: ["sh", "-c", "mysql -h mysql -u root -p$MYSQL_ROOT_PASSWORD -e \"ALTER USER 'root'@'%' IDENTIFIED BY 'newpassword'; FLUSH PRIVILEGES;\""]
      restartPolicy: Never
  backoffLimit: 4
