apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password" # Senha do root
        - name: MYSQL_DATABASE
          value: "wines_db" # Nome do banco de dados
        - name: MYSQL_USER
          value: "user" # Nome do usuário
        - name: MYSQL_PASSWORD
          value: "userpassword" # Senha do usuário
        volumeMounts:
        - name: mysql-data
          mountPath: /var/lib/mysql # Persistência de dados
      volumes:
      - name: mysql-data
        persistentVolumeClaim:
          claimName: mysql-pvc # Associar ao PVC
