apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-service-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: flask-service
  template:
    metadata:
      labels:
        app: flask-service
    spec:
      containers:
      - name: flask-service-container
        image: sodsotnas91/flask-service  # Nome da imagem Docker
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
#  type: NodePort
  selector:
    app: flask-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 30001
  type: NodePort
